### ISSUE TITLE
Add unfurling of URLs in chats

### ISSUE THREAD

**Issue by iurimatias** [status-im/status#2]
originally in: https://github.com/status-im/status-react/issues/11158

### User Story
As a user, I want the app to unfurl URLs so that I can easily see what they refer to without needing to open the URL.

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: If another user shares a URL with me (maybe from a 3rd party app #4605), it would be great if I could see the summary of the content of the URL so I have a quick idea of what it's about.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

1. User receives URL
1. App recognizes URL and uses an unfurlingeloper-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254) library to generate an image (or HTML) content that represents the summary of the URL.

![image](https://user-images.githubusercontent.com/138074/40887892-b768e0f4-674f-11e8-9fe4-4a3324814a23.png)

### Acceptance Criteria

* [ ] Links starting with `http://` or `https://` are unfurled on the receiving client side only for the URLs in the whitelist if enabled
* [ ] Performance is not noticeably negatively impacted by the new functionality
* [ ] The whitelist includes https://github.com

### Security implications
We have to think about the security implications if we do this on the client side (will it be acceptable to access a random URL which might leak metadata about us?)

### Issues

mobile: https://github.com/status-im/status-react/issues/11158
