### ISSUE TITLE
Reduce risk Infura calls exceeding plan

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status#6]
We're exceeding the limit of calls to Infura at relative frequency. The impact of this is unclear, but in control of Infura. This epic captures activities to limit calls, and manage reliance and risk of exceeding our subscription

#### Reduce number of calls to Infura
- [ X] Reduce the number of RPC request by inactive users
- [ ] reduce RPC calls for new accounts by triggering calls depending on behaviour of the user
-  [ ] Move pull to refresh to the main account to make it more easily discoverable
- [ ] Investigate feasibility of moving e2e testing calls to Goerli (cc @cammellos)
- [ ] Investigate current handling of archival data (expensive calls)
- [ ] Investigate combining data saver mode with limited calls
- 08/03/2021 tbd if still accurate: - [ ] Move browser calls to Pocket gateway on testbuild - Isolate wallet calls such that these are not affected (cc @corpetty @cammellos)

#### Remove uncertainty about Infura's handling of exceeding calls
- [ ] Get quote for custom plan _(if Pocket has been tested and proves viable)_

#### Transition to acceptable 'pay per use' solutions
- [ ] Design proposal 'dataplan' allowance, enter own API key 

#### Mitigate abuse of API key
- [ ] Investigate obfuscating and injecting secret in build process to reduce chance of 3rd parties using API key _(we've had 16 Hackerone reports stating that the API key is accessible and can be used for calls outside of the client)_
__________

**We currently have a `Plus monthly subscription` at $1250 /m on Infra budget. Limit is 5.000.000 calls per day. We exceed this limit at irregular frequency.**

**Comment by cammellos** [comment]
Related issue for e2e https://github.com/status-im/status-react/issues/11312

**Comment by iurimatias** [comment]
related https://github.com/status-im/nim-status-client/pull/1260
